name: Commit Style

on:
  pull_request:
    branches: ["**"]
  merge_group:

permissions: {}

jobs:
  check-commit-format:
    runs-on: ubuntu-slim
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Check commit format
        if: github.event_name == 'pull_request'
        uses: Homebrew/actions/check-commit-format@b5fe8cf83919304b3300e0607a2538d40b8749ff
        with:
          check_package_commit_format: false
